### ISSUE TITLE
videotutorial

### ISSUE THREAD

**Issue by elpedriyo** [Wietje/SkyWars#1]
Could you please make a videotutorial, it will be very useful.
I do not understand this: Schematic creation  very well
Thanks

**Comment by Wietje** [comment]
I don't really have the time to make a video tutorial on this, sorry.

**Comment by elpedriyo** [comment]
Ok, I will wait for it alixial, will you post the videotutorial on this page?: http://dev.bukkit.org/bukkit-plugins/skywars-plugin/
