### ISSUE TITLE
Error,

### ISSUE THREAD

**Issue by alixial** [Wietje/SkyWars#2]
I'm rather large noob when it comes to java, so this could be stupidity on my end, but upon importing the source code into eclipse I get the error 

Description Resource    Path    Location    Type
The type org.bukkit.inventory.ItemStack cannot be resolved. It is indirectly referenced from required .class files  ItemUtils.java  /SkyWars-master/src/main/java/vc/pvp/skywars/utilities  line 1  Java Problem

And that's the only error, if you could tell me what i've done wrong. or how to fix it, that'd be great.

**Comment by Wietje** [comment]
You will need to add the Bukkit API to your class path.

**Comment by alixial** [comment]
I did that originally, I figured I wasn't supposed to as after I added it, I received more errors. After spending a while I got it all figured out. Thanks m8. Sorry for the stupid ass question origionaly

**Comment by Wietje** [comment]
A better solution would be to use maven, it would've added the required dependencies to your class path automatically. Glad to see you've fixed your issue.
